
public class ArithmeticException {

	public static void main(String[] args) {
		try
		{
		// TODO Auto-generated method stub
		int num=1;
		System.out.println(num/0);
		}
		catch(Exception ex)
		{
			System.out.println("Arithmetic Exception  caught");
		}
	}

}
